   chunk ::= block

   block ::= {stat} [retstat]

   stat ::=  ‘;’ |
       varlist@variables ‘=’ explist@expressions |
       functioncall |
       label |
       ‘break’ |
       ‘goto’ Name |
       ‘do’ block ‘end’ |
       ‘while’ exp@condition ‘do’ block ‘end’ |
       ‘repeat’ block ‘until’ exp@condition |
       ‘if’ exp@condition ‘then’ block {‘elseif’ exp@condition ‘then’ block} [‘else’ block] ‘end’ |
       ‘for’ Name@variable ‘=’ exp@initializer ‘,’ exp@target [‘,’ exp@step] ‘do’ block ‘end’ |
       ‘for’ namelist@variable ‘in’ explist@iterator ‘do’ block ‘end’ |
       ‘function’ funcname@name funcbody |
+      ‘local’ attnamelist@declarators [‘:’ typelist@type_annotation] [‘=’ explist@initializers] |
       ‘local’ ‘function’ Name@name funcbody |
*      ‘local’ ‘macroexp’ Name@name ‘(’ [parlist@arguments] ‘)’ [‘:’ retlist@return_type] block ‘end’ |
*      ‘local’ ‘record’ Name@name recordbody@record_body |
*      ‘local’ ‘interface’ Name@name recordbody@interface_body |
*      ‘local’ ‘enum’ Name@name enumbody@enum_body |
*      ‘local’ ‘type’ Name@name [typeargs] ‘=’ newtype@value |
*      ‘global’ attnamelist@declarators ‘:’ typelist@type_annotation [‘=’ explist@initializers] |
*      ‘global’ attnamelist@declarators ‘=’ explist@initializers |
*      ‘global’ ‘function’ Name@name funcbody |
*      ‘global’ ‘record’ Name@name recordbody@record_body |
*      ‘global’ ‘interface’ Name@name recordbody@interface_body |
*      ‘global’ ‘enum’ Name@name enumbody@enum_body |
*      ‘global’ ‘type’ Name@name [typeargs] [‘=’ newtype@value]

   attnamelist ::=  Name [attrib@attribute] {‘,’ Name [attrib@attribute]}

   attrib ::= ‘<’ Name ‘>’

   retstat ::= ‘return’ [explist] [‘;’]

   label ::= ‘::’ Name ‘::’

+  funcname ::= Name@base {‘.’ Name} ‘:’ Name@method | Name@base {‘.’ Name} ‘.’ Name@entry

   varlist ::= var {‘,’ var}

   var ::=  Name | prefixexp@object ‘[’ exp@expr_key ‘]’ | prefixexp@object ‘.’ Name@key

   namelist ::= Name {‘,’ Name}

   explist ::= exp {‘,’ exp}

   exp ::=  ‘nil’ | ‘false’ | ‘true’ | Numeral | LiteralString | ‘...’ | functiondef |
       prefixexp | tableconstructor | exp@left binop@op exp@right | unop@op exp@right |
*      exp ‘as’ type | exp ‘as’ ‘(’ typelist ‘)’ | Name ‘is’ type

   prefixexp ::= var | functioncall | ‘(’ exp ‘)’

   functioncall ::=  prefixexp@called_object args@arguments | prefixexp@called_object ‘:’ Name@method args@arguments

   args ::=  ‘(’ [explist] ‘)’ | tableconstructor | LiteralString

   functiondef ::= ‘function’ funcbody

+  funcbody ::= [typeargs@typeargs] ‘(’ [parlist@arguments] ‘)’ [‘:’ retlist@return_type] block ‘end’

+  parlist ::= parnamelist [‘,’ ‘...’ [‘:’ type]] | ‘...’ [‘:’ type]

   tableconstructor ::= ‘{’ [fieldlist] ‘}’

   fieldlist ::= field {fieldsep field} [fieldsep]

   field ::= ‘[’ exp@expr_key ‘]’ ‘=’ exp@value |
+      Name@key [‘:’ type@type] ‘=’ exp@value |
       exp

   fieldsep ::= ‘,’ | ‘;’

   binop ::=  ‘+’ | ‘-’ | ‘*’ | ‘/’ | ‘//’ | ‘^’ | ‘%’ |
       ‘&’ | ‘~’ | ‘|’ | ‘>>’ | ‘<<’ | ‘..’ |
       ‘<’ | ‘<=’ | ‘>’ | ‘>=’ | ‘==’ | ‘~=’ |
       ‘and’ | ‘or’

   unop ::= ‘-’ | ‘not’ | ‘#’ | ‘~’

*  type ::= ‘(’ type ‘)’ | basetype {‘|’ basetype}

*  nominal ::= Name@name {‘.’ Name } [typeargs]

*  basetype ::= ‘string’ | ‘boolean’ | ‘nil’ | ‘number’ | ‘integer’ | ‘any’ | ‘thread’ |
*      ‘{’ type@tuple_type {',' type@tuple_type} ‘}’ | ‘{’ type@key_type ‘:’ type@value_type ‘}’ | functiontype
*      | nominal

*  typelist ::= type {‘,’ type}

*  retlist ::= ‘(’ [typelist] [‘...’] ‘)’ | typelist [‘...’]

*  typeargs ::= ‘<’ typeparam {‘,’ typeparam } ‘>’

*  typeparam ::= Name@name [‘is’ nominal@constraint] | type

*  newtype ::= ‘record’ recordbody | ‘enum’ enumbody | type
*      | ‘require’ ‘(’ LiteralString ‘)’ {‘.’ Name }

*  interfacelist ::= nominal {‘,’ nominal} |
*      ‘{’ type ‘}’ {‘,’ nominal}

*  recordbody ::= [typeargs] [‘is’ interfacelist@is_types]
*      [‘where’ exp@where] {recordentry} ‘end’

*  recordentry ::= ‘userdata’ |
*      ‘type’ Name@name ‘=’ newtype@value | [‘metamethod’] recordkey@name ‘:’ type@type [‘=’ macroexpbody] |
*      ‘record’ Name@name recordbody@record_body | ‘enum’ Name@name enumbody@enum_body | 'interface' Name@name recordbody@interface_body

*  recordkey ::= Name | ‘[’ LiteralString ‘]’

*  enumbody ::= {LiteralString} ‘end’

*  functiontype ::= ‘function’ [typeargs@typeargs] ‘(’ [partypelist@arguments] ‘)’ [‘:’ retlist@return_type]

*  partypelist ::= partype {‘,’ partype} [‘,’ ‘...’ [‘:’ type]] | ‘...’ [‘:’ type]

*  partype ::= Name@name [‘?’] ‘:’ type@type | [‘?’] type@type

*  parnamelist ::= parname {‘,’ parname}

*  parname ::= Name@name [‘?’] [‘:’ type@type]

*  macroexpbody ::= ‘macroexp’ ‘(’ [parlist@arguments] ‘)’ [‘:’ retlist@return_type] block ‘end’
